Title: General Case Information
Version: 0.1
Parameters:
  gender:
    type: string
    description: Gender
  ethnicity:
    type: array
    items:
      type: string
    description: Ethnicity
  sampleCollectionDate:
    type: string
    description: Sample Collection Date
  clinicalIndications:
    type: array
    items:
      type: string
    description: Array of clinical indications example (ICD10:code)
  diseasePanelName:
    type: string
    description: Disease Panel Name